# theme: jekyll-theme-midnight
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/jekyll/minima@v2.5.1

theme: minima

plugins:
  - "jekyll-github-metadata"
  - jekyll-remote-theme
  
username: yupenghe
